services:
  mongodb:
    image: 'mongo:latest'
    container_name: mongo
    ports:
      - '27017'
    volumes:
      - mongo-data:/data/db
  springboot-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot-app
    depends_on:
     - mongodb
    ports:
      - "8080:8080"
    environment:
      - 'JWT_SECRET_PROPS=${JWT_SECRET_PROPS}'

volumes:
  mongo-data: